version: '3'

services:
  tg2sip:
    build:
      context: ./
    container_name: tg2sip
    image: tg2sip
    volumes: 
      - "${DB_LOCATION}:/app/db"
    networks: 
      - telegram
    restart: always

networks: 
  telegram:
    external: true
